# These are supported funding model platforms

custom: ['https://blazeycc.com/pricing.html']
# ko_fi: thekennethy
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
